#!/usr/bin/env python

# www-postprocess.py: post-process HTML files generated by IPython's
# nbconvert program ready for putting on the web

from postprocessing import *
import sys

source_fn = sys.argv[1]
build_dir = sys.argv[2]

try:
    doc = open_html(source_fn, build_dir)

    rewrite_internotebook_links(doc)
    rewrite_title(doc)
    rewrite_mathjax(doc)
    rewrite_embedded_media(doc)
    
    write_html(doc)
    sys.exit(0)
except Exception as ex:
    print ex
    sys.exit(1)
