name             'cncp-worker'
maintainer       'Simon Dobson'
maintainer_email 'simon.dobson@computer.org'
license          'GPL v3'
description      'cncp-worker role'
long_description 'Master recipe list for cncp worker role VM'
version          '0.1.0'
depends          'apt-get-update'
depends          'python-networkx'
depends          'cncp'
