# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise32"
  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.ssh.forward_agent = true

  # Make VM appear on local network
  #config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end

  # Provision machine using local Chef recipes
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "provisioning/cookbooks"

    # Before provisioning, make sure the base box has an
    # up-to-date package tree
    #chef.add_recipe "apt-get-update"

    # Basic networking and NetworkX
    #chef.add_recipe "network-utils"
    #chef.add_recipe "python-networkx"

    # Final set-up for cncp user and engine start-up
    chef.add_recipe "cncp"
  end
end
