# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Build in an Ubuntu environment
  config.vm.box = "ubuntu/trusty32"
  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.ssh.forward_agent = true

  # Make VM appear on local network
  #config.vm.network "public_network"

  # Set up the VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    # Give the VM a sensible name
    vb.name = "complex-networks-complex-processes"

    # Boot with a GUI
    vb.gui = true

    # Need a bigger VM than the default
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Provision machine to build the book
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../provisioning/cookbooks"
    chef.add_recipe "cncp-book"
  end
end
