# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Vagrantfile for network science compute worker VM
#
# Copyright (C) 2015 Simon Dobson
# 
# Licensed under the Creative Commons Attribution-Noncommercial-Share
# Alike 3.0 Unported License (https://creativecommons.org/licenses/by-nc-sa/3.0/).
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # VirtualBox (default) edition
  config.vm.provider "virtualbox" do |vb|
    config.vm.box = "ubuntu/trusty32"
    # config.vm.box_check_update = false

    # Make VM appear on local network
    config.vm.network "public_network"

    # Give the VM a sensible name
    vb.name = "complex-networks-complex-processes-compute"

    # Add more memory for compute nodes
    vb.customize ["modifyvm", :id, "--memory", "4096"]

    # Provision machine as a network science compute node
    config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../provisioning/cookbooks"
      chef.add_recipe "cncp-compute::vm"
    end
  end
end
